import { type NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

// ── Auth guard used by every handler ─────────────────────────────────────────

async function getUser() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  return user;
}

// ── POST /api/admin/banners ───────────────────────────────────────────────────
// Body: { image_url, mobile_image_url, link_url? }
// Inserts a new banner row. The public URLs are generated by the browser after
// uploading directly to the 'banners' Storage bucket.

export async function POST(req: NextRequest): Promise<NextResponse> {
  if (!(await getUser())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: Record<string, unknown>;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }

  const { image_url, mobile_image_url, link_url } = body as {
    image_url:        unknown;
    mobile_image_url: unknown;
    link_url:         unknown;
  };

  if (typeof image_url !== "string" || !image_url ||
      typeof mobile_image_url !== "string" || !mobile_image_url) {
    return NextResponse.json(
      { error: "image_url and mobile_image_url are required strings" },
      { status: 400 },
    );
  }

  const admin = createAdminClient();

  // Place new banner at the end of the list
  const { data: last } = await admin
    .from("banners")
    .select("sort_order")
    .order("sort_order", { ascending: false })
    .limit(1)
    .maybeSingle<{ sort_order: number }>();

  const sortOrder = (last?.sort_order ?? -1) + 1;

  const { data: banner, error } = await admin
    .from("banners")
    .insert({
      image_url,
      mobile_image_url,
      link_url: typeof link_url === "string" && link_url ? link_url : null,
      is_active: true,
      sort_order: sortOrder,
    })
    .select()
    .single();

  if (error) {
    console.error("[banners] insert error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ banner }, { status: 201 });
}

// ── PATCH /api/admin/banners ──────────────────────────────────────────────────
// Body: { ids: string[] }   — new ordered list of all banner IDs
// Batch-updates sort_order so the homepage carousel reflects the new order.

export async function PATCH(req: NextRequest): Promise<NextResponse> {
  if (!(await getUser())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: Record<string, unknown>;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }

  const { ids } = body as { ids: unknown };

  if (!Array.isArray(ids) || ids.some((x) => typeof x !== "string")) {
    return NextResponse.json({ error: "ids must be an array of strings" }, { status: 400 });
  }

  const admin = createAdminClient();

  // Fire individual updates in parallel — acceptable for small banner lists
  const results = await Promise.all(
    ids.map((id: string, index: number) =>
      admin.from("banners").update({ sort_order: index }).eq("id", id),
    ),
  );

  const failed = results.find((r) => r.error);
  if (failed?.error) {
    console.error("[banners] reorder error:", failed.error);
    return NextResponse.json({ error: failed.error.message }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}
